version: '3.4'

services:
  django:
    env_file:
      - .env
      - .devcontainer/.env.local
    restart: "no"
    volumes:
      - ./.devcontainer/docker/geonode/custom_entrypoint.sh:/usr/src/geonode/custom_entrypoint.sh
      - ./.devcontainer/_gitignore:/usr/src/geonode/.gitignore
      - ./.devcontainer/_vscode:/usr/src/geonode/.vscode
    ports:
      - "8001:8001"
    command: /usr/src/geonode/custom_entrypoint.sh

  celery:
    env_file:
      - .env
      - .devcontainer/.env.local
    restart: "no"
    depends_on:
      - django
    # volumes:
    #   - './src:/usr/src/geonode'

  geonode:
    env_file:
      - .env
      - .devcontainer/.env.local
    environment:
      - HTTP_PORT=80

  geoserver:
    env_file:
      - .env
      - .devcontainer/.env.local
    build:
      context: ./.devcontainer/docker/geoserver
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE_VERSION=${GEOSERVER_BASE_IMAGE_VERSION}
    ports:
      - "8080:8080"

  db:
    build:
      context: ./.devcontainer/docker/postgresql
      dockerfile: Dockerfile
    ports:
     - "5432:5432"
